// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 16.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Calculator
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinClient uINClient = this.UICUsersABHMUDesktopRaWindow.UICUsersABHMUDesktopRaClient.UINClient;
            #endregion

            // To test Windows Store apps, use the Coded UI Test project template for Windows Store apps under the Windows Store node.

            // To test Windows Store apps, use the Coded UI Test project template for Windows Store apps under the Windows Store node.

            // Type 'Control + n' in 'N' client
            Keyboard.SendKeys(uINClient, this.RecordedMethod1Params.UINClientSendKeys, ModifierKeys.Control);

            // Type 'Control + v' in 'N' client
            Keyboard.SendKeys(uINClient, this.RecordedMethod1Params.UINClientSendKeys1, ModifierKeys.Control);
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public UICUsersABHMUDesktopRaWindow UICUsersABHMUDesktopRaWindow
        {
            get
            {
                if ((this.mUICUsersABHMUDesktopRaWindow == null))
                {
                    this.mUICUsersABHMUDesktopRaWindow = new UICUsersABHMUDesktopRaWindow();
                }
                return this.mUICUsersABHMUDesktopRaWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private UICUsersABHMUDesktopRaWindow mUICUsersABHMUDesktopRaWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'Control + n' in 'N' client
        /// </summary>
        public string UINClientSendKeys = "n";
        
        /// <summary>
        /// Type 'Control + v' in 'N' client
        /// </summary>
        public string UINClientSendKeys1 = "v";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class UICUsersABHMUDesktopRaWindow : WinWindow
    {
        
        public UICUsersABHMUDesktopRaWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "C:\\Users\\ABHMU\\Desktop\\Radiometer docs\\Cybersecurity\\Patch 6 release\\Patch 6 note" +
                "s.txt - Notepad++";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Notepad++";
            this.WindowTitles.Add("C:\\Users\\ABHMU\\Desktop\\Radiometer docs\\Cybersecurity\\Patch 6 release\\Patch 6 note" +
                    "s.txt - Notepad++");
            this.WindowTitles.Add("new 1 - Notepad++");
            #endregion
        }
        
        #region Properties
        public UICUsersABHMUDesktopRaClient UICUsersABHMUDesktopRaClient
        {
            get
            {
                if ((this.mUICUsersABHMUDesktopRaClient == null))
                {
                    this.mUICUsersABHMUDesktopRaClient = new UICUsersABHMUDesktopRaClient(this);
                }
                return this.mUICUsersABHMUDesktopRaClient;
            }
        }
        #endregion
        
        #region Fields
        private UICUsersABHMUDesktopRaClient mUICUsersABHMUDesktopRaClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class UICUsersABHMUDesktopRaClient : WinClient
    {
        
        public UICUsersABHMUDesktopRaClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "C:\\Users\\ABHMU\\Desktop\\Radiometer docs\\Cybersecurity\\Patch 6 release\\Patch 6 note" +
                "s.txt - Notepad++";
            this.WindowTitles.Add("C:\\Users\\ABHMU\\Desktop\\Radiometer docs\\Cybersecurity\\Patch 6 release\\Patch 6 note" +
                    "s.txt - Notepad++");
            this.WindowTitles.Add("new 1 - Notepad++");
            #endregion
        }
        
        #region Properties
        public WinClient UINClient
        {
            get
            {
                if ((this.mUINClient == null))
                {
                    this.mUINClient = new WinClient(this);
                    #region Search Criteria
                    this.mUINClient.SearchProperties[WinControl.PropertyNames.Name] = "DC-073329  1  Radiometer Patch Release - Level 6 - Project Plan Document  ABL800 " +
                        "SW V6.18 MR1, Hotfix    Project Manager: LARIVProject RD Team: ABHMU, VIJKUIndep" +
                        "endent Reviewer: OJHQA: RAJSIRA: UMEDRTPS&S: CKNAQT R&D: NISKA5-20-2019---------" +
                        "-------------------Started AQT testingDeviations--- 1. No result BNP temperature" +
                        " sensor failure.2. Not able to do RMDED LQC because internal barcode reader is n" +
                        "ot working. Going for non-rmed LQC.steps for AQT---1.production ---- Pass-978155" +
                        "6156618 --- Fake calibrate any one lot number-- should match the catridge lot nu" +
                        "mber2.replace catridge3.on the barcode page --- if 4th digit is 1, its cal catri" +
                        "dge. If 0, its test catridge.d-pisa-temp-resetaud-pisa-pisa.db DC-073433  1  Rad" +
                        "iometer Patch Release - Level 6 - Software Specification   Section 5 approved Re" +
                        "quested Part number   5-21-2019---------------------------- Rajan:- Can write de" +
                        "viation for AQT protocol.  Received Part number - 933-740  5/27/19--------------" +
                        "------- DC-073490 / 1 Radiometer Patch Release - Level 6 - Regression Test Repor" +
                        "t  !Patch6-Sec6 & Ver report Approve   5/28/19--------------------- MD5 generati" +
                        "on:- Get-FileHash -Path .\\RadiometerPatchRelease-Level-003.zip -Algorithm MD5  -" +
                        "-------------------------------------------------------------------------  Hi Al" +
                        "l,We have accomplished the verification phase and have signed off till section 8" +
                        " of the plan document .Currently we are on track as per the schedule planned.Req" +
                        "uesting you to kindly have a look on the advancement of the documents post the G" +
                        "o\\NoGo meeting. Following is the list of the documents:-1.\tDC-073329 / 4 Radiome" +
                        "ter Patch Release - Level 6 - Project Plan Document2.\tDC-073490 / 2 Radiometer P" +
                        "atch Release - Level 6 - Regression Test Report3.\tDC-073433/2  Radiometer Patch " +
                        "Release - Level 6 - Software Specification  4.\tDC-073511  1  Radiometer Patch Re" +
                        "lease - Level 6 - Hotfix release decision meeting minutes  (Draft)5.  DC-073405/" +
                        "1   Radiometer Patch Release - Level 6 - Go\\NoGo Mom Please revert back if you f" +
                        "ind any issue, as early as possible. This will enable us to be more prepared for" +
                        " the upcoming Release decision meeting, scheduled on 3rd June.Requesting all to " +
                        "kindly review and verify the following:-1. DC-073329/9 Radiometer Patch Release " +
                        "- Level 6 - Project Release Report2.  Appendix 1_1(Deliverables List) attached t" +
                        "o the above release report.3. DC-073511/1  Radiometer Patch Release - Level 6 - " +
                        "Hotfix release decision meeting minutes";
                    this.mUINClient.WindowTitles.Add("C:\\Users\\ABHMU\\Desktop\\Radiometer docs\\Cybersecurity\\Patch 6 release\\Patch 6 note" +
                            "s.txt - Notepad++");
                    this.mUINClient.WindowTitles.Add("new 1 - Notepad++");
                    #endregion
                }
                return this.mUINClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUINClient;
        #endregion
    }
}
